### ISSUE TITLE
Status bar loses file path and cursor position when Termination active

### ISSUE THREAD

**Issue by mc-funk** [Fred-Barclay/Termination#12]
I just installed Termination this morning and had to de-activate it because of the following: 

When Termination is installed and active, the file name and cursor position disappear from the status bar. I could not find anything in the settings that would allow me to impact this. 
<img width="1126" alt="screen shot 2016-11-18 at 1 22 32 pm" src="https://cloud.githubusercontent.com/assets/10001418/20444093/4bb7a0a4-ad95-11e6-863b-007aa31553e4.png">

When I de-activate Termination it goes back to the expected behavior: 
<img width="1133" alt="screen shot 2016-11-18 at 1 42 14 pm" src="https://cloud.githubusercontent.com/assets/10001418/20443988/dd74d134-ad94-11e6-89eb-d4d28db1ae03.png">

**Comment by Fred-Barclay** [comment]
Hi mc-funk. That's sort of an accidental feature. :laughing: I didn't mean to code it in initially, but I liked it once I figured out what was going on. The file name and cursor position are actually still there, but you have to hover over the status bar and scroll down to see them, then scroll back up to return to the terminal. I'd kept this because I liked having almost all of the status bar devoted to termination.

But it's definitely problematic for some users (like you) so there's a way around it:
Go to Termination's settings (`ctrl-,`, "Packages", then look for termination and click "Settings")
Tick "Clone Terminal Plus"
Restart Atom

Thanks for the issue! I'm going to consider ways to make this easier to understand or get rid of entirely since you've pointed this out. :+1: 

Cheers,
Fred

**Comment by mc-funk** [comment]
Oh, fantastic, that checkbox got me where I needed to be. Thanks so much for the prompt response! I have been having terminal-plus heartache with it not working and didn't want to deal with it -- ( and I also like the ctrl + ` keymapping a lot better than overwriting the cmd + shift + t undo-close-tab behavior, as other packages do!  ... So, awesome. Thanks again!

**Comment by Fred-Barclay** [comment]
No worries. Thank **you!**
