### ISSUE TITLE
Cart type anything just a blinking light

### ISSUE THREAD

**Issue by Tms157** [Fred-Barclay/Termination#30]
Hello, i cart seem to get any terminal package to work heres a screenshot: http://imgur.com/a/CZqcV

I have node-gyp installed and heres my other pakages: 

Remote-FTP@0.10.5
atom-material-ui@1.3.9
autocomplete-wordpress-hooks@0.2.2
autoprefixer@3.6.1
color-picker@2.2.5
double-tag@0.4.0
emmet@2.4.3
file-icons@2.0.15
highlight-selected@0.12.0
imdone-atom@2.1.18
language-ejs@0.4.0
linter@1.11.21
linter-jshint@3.0.2
linter-php@1.3.1
minimap@4.26.8
node-debugger@1.10.1
pigments@0.39.0
project-manager@3.3.3
sass-autocompile@0.13.3
seti-icons@1.3.4
todo-show@1.11.0
wordpress-api@1.2.2

**Comment by Fred-Barclay** [comment]
Hi @Tms157 
Can I grab this information from you? https://github.com/Fred-Barclay/Termination/blob/master/CONTRIBUTING.md#filing-an-issue It makes debugging (and hopefully fixing) a bit easier. :smiley:

**Comment by Tms157** [comment]
Version of Atom: Latest (1.14.3)
Version of Termination: latest (0.3.7)
Operating System: MacOS sierra 10.12.3 (16D32)
Any debug information: jus installed it and it dint work dont really have much more
Steps to reproduce the problem: Just install it

Could i be missing something i need to be able to use this or something? i could not get any terminal to work.

**Comment by isaac-webb** [comment]
@Fred-Barclay I've had this issue repeatedly with `terminal-plus` and `termination`. Ended up debugging and the problem is in `termination.coffee`.

For some reason, `process.env.SHELL` never seems to be defined, so the line that uses that variable errors. Fixed it by replacing `process.env.SHELL` with `/bin/bash`. Unfortunately, I don't know enough about Atom to fix it myself, but thought I'd share the problem with you!

**Comment by Tms157** [comment]
@isaac-webb what file did you make this change in?

**Comment by isaac-webb** [comment]
@Tms157 `~/.atom/packages/termination/lib/termination.coffee` Line 83, I changed `process.env.SHELL` to `'/bin/bash'`

**Comment by Tms157** [comment]
@isaac-webb Thanks! will give this a go in the morning

**Comment by Fred-Barclay** [comment]
Awesome @isaac-webb ! I hope this helps @Tms157 :smile: and you're definitely helping me figure out the problem. 

Can you walk me through the steps you used to debug and find this? I'm still inexperienced working with coffeescript and electron.

Side note:
Changing `process.env.SHELL` to `/bin/bash` isn't a solution for the entire program since we have Windows users (and maybe some Linux users without bash???) so I'll work on a long-term solution. If we get this fixed I'll push it upstream to platformio as well (I remember seeing similar bugs on their repo).

Cheers!
Fred

**Comment by isaac-webb** [comment]
@Fred-Barclay I just used Atom's built-in Chrome web debugger. There was a warning when the package loaded relating to the `shell` variable being `null` so I found the definition in the `termination.coffee` file and noticed that `process.env.SHELL` does not seem to exist on macOS (figured this out by using the console to view the `process.env` object). In addition, an error was thrown whenever a terminal opened since it was trying to assess a `null` path. 

As a side note, I think a better quick fix, if not permanent, would be replacing `process.env.SHELL` with `process.env.SHELL || '/bin/bash'`. If it isn't defined, then it will fallback to bash. Tried Atom on a Linux VM and that variable seems to be defined, so I'm willing to bet that fallback would apply mainly to macOS users, who are almost guaranteed to have bash.

Unfortunately, I'm sure you are far more experienced with CoffeeScript and Electron, so I'm not sure I can provide too much more insight, but I hope this helped!

-Isaac

**Comment by Fred-Barclay** [comment]
I've got two ideas so far:
add `process = require 'process'` to the top of termination.coffee
or
add this under line 83:
```
else if process.platform is 'darwin'
  /bin/bash
```

I don't have Mac hardware so I'd need someone to test this and help me out. :stuck_out_tongue_winking_eye:

**Comment by isaac-webb** [comment]
I think either of the latter two options would work, @Fred-Barclay ! The "fallback" fix might be nice for Linux users who somehow do not have a shell defined. I tested the first option, and it didn't make much of a difference, likely because the `process.env` object does exist, it just doesn't have a `SHELL` property.

I made another interesting discovery this morning, however... I, as most macOS users probably do, tend to launch Atom from Spotlight or Launchpad. Out of curiosity, I executed `atom` in iTerm to launch it instead. When I did this, the `SHELL` variable was defined! So it appears as though this bug may be due to the lack of an executing shell when launching an app "normally" on macOS? Just another reason we should all use a terminal... or Linux 😉

**Comment by Tms157** [comment]
@Fred-Barclay , @isaac-webb thanks foe the help guys! working fine now.

**Comment by Fred-Barclay** [comment]
Great news @Tms157!

I'll push out an update in a few moments with `process.env.SHELL || '/bin/bash'`. I'm also going to kick this upstream as an Issue. Considering that they have 3 similar issues on their repo they might be interested in this fix or have some other suggestions.

@isaac-webb Linux rocks! Just sayin'... 
Thanks for the help and the fix!

**Comment by Fred-Barclay** [comment]
Wow, @ivankravets works fast! This is fixed and released for platformio-ide-terminal as well:
https://github.com/platformio/platformio-atom-ide-terminal/commit/112c963f5edbcf203a52a47c107bc6587894bc15
