### ISSUE TITLE
How to fix key repeat on macOS

### ISSUE THREAD

**Issue by steakknife** [Fred-Barclay/Termination#9]
Right now, this happens in most all terminal-plus forks I've tried (not in the editor, obviously).

Hold <kbd>e</kbd> key... should get a bunch of e's.

![img](http://content.screencast.com/users/xzxzxzxx/folders/Jing/media/681d66a9-8dd3-491b-8010-88314dd8fdbf/00000063.png)

Disabling `ApplePressAndHoldEnabled` is not an option.

**Comment by Fred-Barclay** [comment]
Hmmm... so you should get a string of e's  but instead you get that popup with different options for the e character?
That's odd. I don't have a Mac and it does not occur in Linux so I may not be able to find the root cause, but I will take a look at it.

Question: does/did it occur in terminal-plus itself, or only in the forks that you've tried?

**Comment by steakknife** [comment]
macOS only. Happens on all terminals I've tried that work on 1.12 beta.

There must be a CSS property or function call which turns off accent mode input mode because the editor works property while panels don't (at least by default).

```
❯❯❯ apm-beta list                                                                                                       ⏎ ✖ ✱ ◼
Built-in Atom Packages (89)
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.52.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.45.0
├── base16-tomorrow-dark-theme@1.3.0
├── base16-tomorrow-light-theme@1.3.0
├── one-dark-ui@1.6.2
├── one-light-ui@1.6.2
├── one-dark-syntax@1.5.0
├── one-light-syntax@1.5.0
├── solarized-dark-syntax@1.0.5
├── solarized-light-syntax@1.0.5
├── about@1.7.0
├── archive-view@0.62.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.13.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.4
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.1
├── bookmarks@0.42.0
├── bracket-matcher@0.82.2
├── command-palette@0.39.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.40.0
├── find-and-replace@0.202.0
├── fuzzy-finder@1.4.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.2
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── line-ending-selector@0.5.0
├── link@0.31.2
├── markdown-preview@0.158.8
├── metrics@1.1.1
├── notifications@0.65.1
├── open-on-github@1.2.1
├── package-generator@1.0.1
├── settings-view@0.243.1
├── snippets@1.0.3
├── spell-check@0.68.4
├── status-bar@1.4.1
├── styleguide@0.47.2
├── symbols-view@0.113.1
├── tabs@0.103.0
├── timecop@0.33.2
├── tree-view@0.210.0
├── update-package-dependencies@0.10.0
├── welcome@0.35.1
├── whitespace@0.35.0
├── wrap-guide@0.38.2
├── language-c@0.54.0
├── language-clojure@0.22.1
├── language-coffee-script@0.48.0
├── language-csharp@0.12.1
├── language-css@0.40.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.43.0
├── language-html@0.46.1
├── language-hyperlink@0.16.1
├── language-java@0.24.0
├── language-javascript@0.122.0
├── language-json@0.18.3
├── language-less@0.29.6
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.3
├── language-property-list@0.8.0
├── language-python@0.45.1
├── language-ruby@0.70.2
├── language-ruby-on-rails@0.25.1
├── language-sass@0.57.0
├── language-shellscript@0.23.0
├── language-source@0.9.0
├── language-sql@0.25.0
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.12
└── language-yaml@0.27.1

Community Packages (89) {{~}}/.atom/packages
├── activate-power-mode@1.1.0
├── aligner@0.22.2
├── aligner-css@1.2.0
├── aligner-javascript@1.0.0
├── aligner-ruby@1.5.0
├── aligner-scss@1.1.0
├── angular-2-typeScript-snippets@0.6.3
├── atom-beautify@0.29.13
├── atom-handlebars@1.3.0
├── atom-html-preview@0.1.22
├── atom-htmltidy@5.1.0
├── atom-rails-debugger@0.2.1
├── atom-runner@2.7.1
├── atom-typescript@10.1.12
├── autocomplete-go@1.3.0
├── autocomplete-modules@1.6.7
├── autocomplete-ruby@0.2.0
├── bootcut-syntax@0.0.9
├── browser-plus@0.0.76
├── build@0.66.0
├── builder-go@1.0.1
├── busy@0.7.0
├── dash@1.7.0
├── ex-mode@0.13.1
├── file-icons@1.7.24
├── gist@0.3.1
├── gist-it@0.9.1
├── git-blame@0.4.11
├── git-diff-details@1.4.0
├── git-plus@5.24.1
├── git-time-machine@1.5.3
├── go-config@1.2.4
├── go-debug@0.1.22
├── go-get@2.1.1
├── go-plus@4.3.2
├── godoc@1.1.1
├── gofmt@1.2.0
├── gometalinter-linter@1.2.2
├── gorename@1.1.0
├── keybinding-cheatsheet@0.1.1
├── language-babel@2.48.1
├── less-autocompile@1.0.0
├── linter@1.11.18
├── linter-golinter@1.2.1
├── linter-handlebars@2.3.4
├── linter-jshint@3.0.1
├── linter-rails-best-practices@0.2.2
├── linter-ruby@1.2.2
├── linter-sass-lint@1.7.4
├── linter-scss-lint@3.0.4
├── linter-shellcheck@1.4.1
├── linter-tidy@2.2.1
├── livereload@0.4.4
├── minimap@4.25.6
├── minimap-autohide@0.10.1
├── minimap-cursorline@0.2.0
├── minimap-git-diff@4.3.1
├── minimap-hide@0.3.0
├── minimap-linter@1.6.0
├── minimap-pigments@0.2.1
├── minimap-selection@4.4.0
├── minimap-split-diff@0.3.2
├── navigator-go@1.1.3
├── open-in-browsers@0.0.19
├── pigments@0.37.0
├── pp@0.0.1
├── pp-js@0.0.2
├── pp-markdown@0.0.2
├── project-manager@3.3.3
├── rails-finder@0.7.0
├── rails-i18n@0.1.3
├── rails-i18n-autocomplete@0.4.0
├── rails-latest-migration@1.1.6
├── rails-model-schema@0.9.0
├── rails-open-rspec@1.2.0
├── rails-partials@0.9.2
├── rails-rspec@0.3.2
├── rails-snippets@2.9.0
├── rails-transporter@1.6.5
├── ruby-block@0.3.5
├── ruby-bundler@0.3.0
├── ruby-navigator@0.5.0
├── ruby-syntax-replacer@0.5.1
├── ruby-test@0.9.17
├── ruby-test-switcher@1.2.3
├── tabularize@0.2.5
├── tester-go@2.0.2
├── vim-mode@0.65.1
└── vim-modeline@0.4.2

Git Packages (2) {{~}}/.atom/packages
├── dash-on-cursor@0.1.0 (stanaka/dash-on-cursor#785714d5)
└── termination@0.3.1 (Fred-Barclay/Termination#3f27691b)
```

**Comment by steakknife** [comment]
Found it https://github.com/atom/atom/blob/master/src/text-editor-component.coffee#L253

**Comment by steakknife** [comment]
Basically, adding three event listeners somewhere to workaround it.

**Comment by steakknife** [comment]
Trying on 1.12.0 stable, it should be the same.

**Comment by steakknife** [comment]
Related [SO answer about how to fix it in JS](https://stackoverflow.com/questions/381795/how-to-disable-right-click-context-menu-in-javascript)

**Comment by Fred-Barclay** [comment]
I wonder if something like this would work?
```
require os
detectAccentedCharacterMenu: ->
  if os = <whatever macOS's identifier is in coffescript
    @domNode.addEventListener 'keydown', (event) =>
        if lastKeydownBeforeKeypress
          if lastKeydownBeforeKeypress.keyCode is event.keyCode
            @openedAccentedCharacterMenu = false
          lastKeydownBeforeKeypress = null
```
Trouble is I don't have a mac and I'm not sure how to integrate this, or if it would override https://github.com/atom/atom/blob/master/src/text-editor-component.coffee#L253 

Thoughts?

**Comment by steakknife** [comment]
Might work

os.platform() == "darwin"

**Comment by steakknife** [comment]
The trick is to change the selection area in webkit to cancel the menu, so
the user never sees it. This is what the text editor does, but Termination
view is based on a completely different view than the text editor IIRC.

**Comment by steakknife** [comment]
BTW: Level of effort to just prototype from an editor view, which already
has the right behavior?

**Comment by Fred-Barclay** [comment]
If you want to try this from your end, please do! If you get it fixed please send in a pull request and I'll be sure to merge it in. There's just not really anything I can do on my end without a Mac to test with. :cry:  If it were a cross-platform bug it would be different, but I have no way of knowing if my changes would work or not or if I could be breaking something else.

**Comment by steakknife** [comment]
You contributed nothing but forking and expect everyone else to maintain your code. That doesn't help. I maintain Linux, Windows and macOS VMs, and you should too. Otherwise just say "Windows only" and few people will ever use this fork.

**Comment by Fred-Barclay** [comment]
I'm sorry you feel that way. I'm not willing to use a hackintosh since it is not legal. Hard work indeed makes a project unique, and I am not going to steal the hard work of the unique and talented programmers at Apple. (Context note: I am not a Mac fanboy and I've never owned any Apple product.)

I'm not willing to commit changes that aren't tested/I have no way of knowing how they work or if they will break things for other users. That's just common sense, not expecting other people to maintain my code. If you look over the Issues here you'll find that I have, and will continue to, fix problems myself. In your case, however, this is clearly a Mac-specific issue which I have no way of testing or fixing myself. That is why I invited you to help, not because I expect you to maintain my code. I simply cannot fix something that I have no ability to test! :wink:

I maintain Linux and Windows machines myself (though I'm far more familiar with Linux) and this project is certainly not Windows only.

It is true that I have contributed little to date besides forking and design changes. This is a young project and we're just getting a sense of direction. On the other hand, this is a terminal that offers a solution to the current terminal-plus issues. That's not a small task.

I did invite you to do any testing on your Mac if you're willing. You don't seem to be so let's leave this issue closed. If in the future you change your mind you're more than welcome to contribute constructively.

Until then, you're welcome to use whatever you like. I can't change your mind about me, or termination, but I will ask you to take a step back and evaluate the situation with a more open mind.
